// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZlRydWO_AeTZ-V55qow_i407FfEZOlco',
    appId: '1:618226115239:web:7b92ddceeb653c9b813182',
    messagingSenderId: '618226115239',
    projectId: 'whatsapp-backend-2adca',
    authDomain: 'whatsapp-backend-2adca.firebaseapp.com',
    storageBucket: 'whatsapp-backend-2adca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZYZctQ__dXsLWcbrljmRb9PBsOmNriIs',
    appId: '1:618226115239:android:34ef7d9034a8b01c813182',
    messagingSenderId: '618226115239',
    projectId: 'whatsapp-backend-2adca',
    storageBucket: 'whatsapp-backend-2adca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv0ZA7ALUg2xrJQIFg3_oBKXpxbVRcKGI',
    appId: '1:618226115239:ios:39002dae12e87695813182',
    messagingSenderId: '618226115239',
    projectId: 'whatsapp-backend-2adca',
    storageBucket: 'whatsapp-backend-2adca.appspot.com',
    iosClientId: '618226115239-39jb0gj76o1hecv60q14sb344hnce2h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv0ZA7ALUg2xrJQIFg3_oBKXpxbVRcKGI',
    appId: '1:618226115239:ios:f545584117f733f2813182',
    messagingSenderId: '618226115239',
    projectId: 'whatsapp-backend-2adca',
    storageBucket: 'whatsapp-backend-2adca.appspot.com',
    iosClientId: '618226115239-jl1m7ii4nui1pjjvpmmiofo1il381jnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter.RunnerTests',
  );
}
